// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoWLcjQRYrSjZ39tAdApZbLjKselnUIIg',
    appId: '1:96444590784:web:8e4f49ef648d2849419b25',
    messagingSenderId: '96444590784',
    projectId: 'commerceproject-f227c',
    authDomain: 'commerceproject-f227c.firebaseapp.com',
    storageBucket: 'commerceproject-f227c.appspot.com',
    measurementId: 'G-DJMYZNY28B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwio5yiRnWPQywg0j_ZGbMJRjSE2-Xtbw',
    appId: '1:96444590784:android:3049b609648fec09419b25',
    messagingSenderId: '96444590784',
    projectId: 'commerceproject-f227c',
    storageBucket: 'commerceproject-f227c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwvBnpI2KyU9-e7kqeYKuKwdcq6mK2KN0',
    appId: '1:96444590784:ios:5fef5d3cb3096fef419b25',
    messagingSenderId: '96444590784',
    projectId: 'commerceproject-f227c',
    storageBucket: 'commerceproject-f227c.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwvBnpI2KyU9-e7kqeYKuKwdcq6mK2KN0',
    appId: '1:96444590784:ios:03071e149fccf2d3419b25',
    messagingSenderId: '96444590784',
    projectId: 'commerceproject-f227c',
    storageBucket: 'commerceproject-f227c.appspot.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
